### ISSUE TITLE
corrupting saves?

### ISSUE THREAD

**Issue by jeffythedragonslayer** [Ryzee119/n64_controller_test#4]
Hi there; I'm curious what is so dangerous about this test that this warning is included?

> WARNING: This has the potential the corrupt your saved games. Use with caution.

**Comment by jeffythedragonslayer** [comment]
I assume you mean saved games on the Controller Pak.

**Comment by Ryzee119** [comment]
It has the ability to write random data to the mempak for test.
This would corrupt any saved games on the mempak you happened to overwrite

**Comment by jeffythedragonslayer** [comment]
Ok, thanks.
